# Generated by Django 5.1.7 on 2025-05-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_shoe_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
